# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Agnès Haasser
email: agnes@corelka.fr
description: >- # this means to ignore newlines until "baseurl:"
  Consultante en qualité web
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.corelka.fr" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  tut-tuuut

language: fr

author: Agnès Haasser

# Theme settings
# see https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml
navbar-links:
  CV: "cv.html"
  Qualité: "qualite-web.html"
  Développement: "developpement.html"
  Conférences: "conferences.html"
  Contact: "contact.html"

avatar: "/assets/img/agnes-small.jpg"
show-avatar: true
round-avatar: true

social-network-links:
  email: "agnes@corelka.fr"
  github: tut-tuuut
  linkedin: agneshaasser

# Build settings
markdown: kramdown
remote_theme: daattali/beautiful-jekyll

plugins:
  - jekyll-feed

url-pretty: "corelka.fr"

navbar-col: "#A80355"
navbar-text-col: "#FFFFFF"
navbar-border-col: "#8F0348" #"#EAEAEA"
page-col: "#FFFFFF"
link-col: "#A80355"
hover-col: "#8F0348"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.
#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# Ruby Date Format to show dates of posts
date_format: "%-d %B %Y"
timezone: "Europe/Paris"

# Default YAML values (more information on Jekyll's site)  
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false  # add comments to all blog posts 		
      show-share: false # add sharing buttons to all blog posts		
      show-subscribe: falsee # add subscribe email to all blog posts
      addthis-plugin: true
      carbonads: true
      datacampcourse: true
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - CNAME
  - LICENSE
  - README.md
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
